[package]
name = "auth-server"
version = "1.3.2"
authors = ["Tobias Tangemann <tobias@tangemann.org>"]
description = "Service for authenticating requests from nginx (ngx_http_auth_request_module)."
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
actix-web = { version = "4.4", default-features = false, features = ["macros", "cookies"] }
clap = { version = "4.4.8", features = ["derive", "env"] }
cookie = "0.18"
jsonwebtoken = { version = "9.1", default-features = false }
log = "0.4.20"
serde = "1.0.192"
simple_logger = { version = "4.2.0", default-features = false }
time = { version = "0.3.30", features = ["formatting"] } # must match dependency in cookie
tokio = { version = "1.34.0", features = ["macros"] }
#mimalloc = { version = "^0.1.32", default-features = false }

[dev-dependencies]
base64 = "0.21.5"
serde_json = "1.0.108"
tempfile = "3.8.1"

[features]
systemd_socket_activation = ["libsystemd", "futures"]

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27.1", features = ["fs", "user"] }

[target.'cfg(target_os = "linux")'.dependencies]
futures = { version = "0.3.29", optional = true }
libsystemd = { version = "0.7.0", optional = true }

[profile.release]
#debug = true
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.dev]
split-debuginfo = "unpacked"
