[package]
name = "auth-server"
version = "1.2.3"
authors = ["Tobias Tangemann <tobias@tangemann.org>"]
description = "Service for authenticating requests from nginx (ngx_http_auth_request_module)."
edition = "2021"

[dependencies]
actix-web = { version = "4", default-features = false, features = [ "macros", "cookies" ] }
tokio = { version = "1", features = [ "macros" ] }
futures = { version = "0.3", optional = true }
log = "0.4"
simple_logger = { version = "4.0", default-features = false }
serde = "1.0"
jsonwebtoken = { version = "8", default-features = false }
time = { version = "0.3", features = ["formatting"] } # must match dependency in cookie
cookie = "0.17"
clap = { version = "4.0", features = ["derive", "env"] }
#mimalloc = { version = "^0.1.32", default-features = false }

[dev-dependencies]
base64 = "0.21"

[features]
systemd_socket_activation = ["libsystemd", "futures"]

[target.'cfg(unix)'.dependencies]
nix = "^0.26"

[target.'cfg(target_os = "linux")'.dependencies]
libsystemd = { version = "^0.6", optional = true }

[profile.release]
#debug = true
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.dev]
split-debuginfo = "unpacked"
