[package]
name = "auth-server"
version = "1.2.0"
authors = ["Tobias Tangemann <tobias@tangemann.org>"]
description = "Service for authenticating requests from nginx (ngx_http_auth_request_module)."
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = [ "macros" ] }
log = "^0.4"
simple_logger = { version = "^2.1", default-features = false }
serde = "^1.0"
jsonwebtoken = { version = "8", default-features = false }
time = { version = "0.3.5", features = ["formatting"] } # must match dependency in cookie
cookie = "^0.16"
clap = { version = "3.0", features = ["derive", "env"] }
mimalloc = { version = "^0.1.29", default-features = false }

[dev-dependencies]
base64 = "0.13"

[features]
default = ["systemd_socket_activation"] 
systemd_socket_activation = ["libsystemd"]

[target.'cfg(unix)'.dependencies]
nix = "^0.23"

[target.'cfg(target_os = "linux")'.dependencies]
libsystemd = { version = "^0.5", optional = true }

[profile.release]
#debug = true
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.dev]
split-debuginfo = "unpacked"
