[package]
name = "auth-server"
version = "1.1.2"
authors = ["Tobias Tangemann <tobias@tangemann.org>"]
description = "Service for authenticating requests from nginx (ngx_http_auth_request_module)."
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
log = "^0.4"
simple_logger = {version = "^2.1", default-features = false }
serde = "^1.0"
regex = "^1.5"
jsonwebtoken = {version = "8", default-features = false }
time = {version =  "0.3.5", features = ["formatting"] } # must match dependency in cookie
cookie = "^0.16"
tokio-stream = { version = "0.1.7", features = ["net"] }
clap = { version = "3.0", features = ["derive", "env"] }

[dev-dependencies]
base64 = "0.13"

[target.'cfg(unix)'.dependencies]
nix = "^0.23"

[profile.release]
#debug = true
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = "symbols"

[profile.dev]
split-debuginfo = "unpacked"
