
name: CI
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v2
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v2
        with:
          command: test
          args: --release
      - uses: actions-rs/cargo@v2
        with:
          command: build
          args: --release --locked --all-features
