
name: CI
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust (Stable)
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Build
        run: cargo build --release --locked --all-features
      - name: Run Tests
        run: cargo test --release
